#define object
#define model
#define protocol
#define singleton
#define definition(stuff)
#define instance(stuff)
#define accessor(stuff)
#define getter(stuff)
#define setter(stuff)
#define initialize(stuff)
#define defer(stuff)
#define implements
#define NamedController(stuff)
#define Data(stuff)
#define Messages(stuff)
#define ThreadSafe(stuff)
#define data1
#define self
struct NamedController{};