#!/bin/sh

echo "Running \`test1.zc\`" && ./zircon test1.zc; echo
echo "Running \`test2.zc\`" && ./zircon test2.zc; echo
echo "Running \`test3.zc\`" && ./zircon test3.zc; echo
echo "Running \`test4.zc\`" && ./zircon test4.zc; echo
#echo "Running \`test5.zc\`" && ./zircon test5.zc; echo
#echo "Running \`test6.zc\`" && ./zircon test6.zc; echo
echo "Running \`test7.zc\`" && ./zircon test7.zc; echo
echo "Running \`test8.zc\`" && ./zircon test8.zc; echo
echo "Running \`test9.zc\`" && ./zircon test9.zc; echo
#echo "Running \`test10.zc\`" && ./zircon test10.zc; echo

echo "Running \`keywords.zc\`" && ./zircon keywords.zc; echo
echo "Running \`Point2.zc\`" && ./zircon Point2.zc; echo
echo "Running \`Composition.zc\`" && ./zircon Composition.zc; echo
echo "Running \`Inheritance.zc\`" && ./zircon Inheritance.zc; echo
echo "Running \`objects/main2.zc\`" && ./zircon objects/main2.zc; echo

echo "Running \`Circle.zc\` \`Point.zc\` \`main.zc\`"
./zircon objects/main.zc objects/Circle.zc objects/Point.zc
