#import "Object"

#include <stdlib.h>

object Test implements Object((int): aValue, (int): bValue) {
    fields {
        int a;
        int b;
    }

    init {
        self->a = aValue;
        self->b = bValue;
    }

    defer {}

    (void) self |> "test no param" |> self->a = 42;
    (void) self |> "test with 2 param" |> (int): a, (int): b |> self->a = a;
    (void) self |> "test compound statement no param" |> {
        self->a = 422;
    }
    (void) self |> "test compound statement one param" |> (int): a, (int): b |> {
        self->a = a;
    }
}

void main(void) {
    return;
}
